name: sse
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - tqdm
  - geopy
  - tabulate
  - numpy
  - seaborn
  - cartopy
  - scipy
  - matplotlib
  - scikit-learn
  - shapely
  - obspy
  - utm
